---
# Copyright (c) 2017 Intel Corporation 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Install packages
  yum: name={{ item }} state=present
  with_items:
  - keepalived
  - psmisc

- name: Allow connections between infrastructure nodes
  template:
    src: firewall.sh.j2
    dest: /tmp/firewall.sh
    mode: "u=rwx,g=,o="

- command: /tmp/firewall.sh

- file: 
    path: /tmp/firewall.sh
    state: absent 

- name: Generate random internal password
  shell: uuidgen
  run_once: true
  register: keepalived_internal_pass

- name: Generate random external password
  shell: uuidgen
  run_once: true
  register: keepalived_external_pass

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Start keepalived
  service: 
    name: keepalived
    state: started
    enabled: yes

- service:
    name: keepalived
    state: restarted
