- name: Pull etcd container
  command: docker pull {{ etcd_image }}
  register: pull_result
  changed_when: "'Downloaded newer image' in pull_result.stdout"

- name: Install etcd container service file
  template:
    dest: "/etc/systemd/system/etcd_container.service"
    src: etcd.docker.service
  register: install_etcd_result

- name: Reload systemd
  command: systemctl daemon-reload

- name: Ensure etcd datadir exists
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    mode: 0700

- name: Generate certificates
  include: certificates.yml

- name: Create etcd config file for new instancie
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    backup: true

- name: Remove all quotations
  replace:
    dest: /etc/etcd/etcd.conf
    regexp: '"'
    replace: ''

#- name: Restart etcd
#  service:
#    name: etcd_container
#    state: started

- name: Restart and enable etcd
  service:
    name: etcd_container
    state: restarted
    enabled: yes
  register: start_result
